apiVersion: v1
kind: Service
metadata:
  name: registy-ui
  labels:
    app: registry
spec:
  selector:
    app: registry
    tier: registry
  ports:
  - port: 8000
    targetPort: 8000
    name: registry
  type: NodePort
    