apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
        tier: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
          name: registry
        volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
        - name: registry-persistent-storage
          mountPath: /var/lib/registry
      - name: registryui
        image: hyper/docker-registry-web:latest
        ports:
        - containerPort: 8080
        env:
        - name: REGISTRY_NAME
          value: cluster-registry
        - name: REGISTRY_URL
          value: http://localhost:5000/v2
      volumes:
        - name: docker
          hostPath:
            path: /var/run/docker.sock
        - name: registry-persistent-storage
          persistentVolumeClaim:
            claimName: registry-claim
          
      