apiVersion: v1
kind: Service
metadata:
  name: registy-ui
  labels:
    app: registry
spec:
  selector:
    app: registry
    tier: registry
  ports:
  - port: 8080
    targetPort: 8080
    name: registry
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  type: NodePort
  selector:
    app: registry
    tier: registry
  ports:
  - name: registry
    port: 5000
    targetPort: 5000
    nodePort: 30400