apiVersion: v1
kind: PersistenVolume
metadata:
  name: registry
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/docker-registry/"

---
apiVersion: v1
kind: PersistenVolumeClaim
metadata:
  name: registry-claim
